#!/bin/bash

#List here all the f90 files to compile, separated by spaces
#THERE MUST NOT be spaces around '=' in bash
myprogramfiles="command_line.f90 create_axis.f90 helpers.f90  w_netcdf.f90 main.f90"

#Name of compiled file
outfile="output_file"

#Name of compiler
fc=gfortran
#Use nf-config to grab the compile and link flags. Backticks run command and grab output
fflags=`-I/usr/include`
flibs=`-L/usr/lib -lnetcdff -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -lnetcdf -lnetcdf -ldl -lz -lcurl -lm`

#Actual compile line. Other flags etc can be added
$fc -g -std=f2008 $fflags $myprogramfiles $flibs -o $outfile
